### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by newtonker** [jarlen/PhotoEditDemo#1]
在小米2 Android 5.0.2 和小米3 Android 4.4.4上跑demo，滤镜功能无法使用。一点测试就闪退，提示NativeFilters找不到filters库。
附log:
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.jarlen.picturetest-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libfilters.so"
            at java.lang.Runtime.loadLibrary(Runtime.java:366)
            at java.lang.System.loadLibrary(System.java:989)
            at com.js.photosdk.filter.NativeFilters.<clinit>(NativeFilters.java:6)
            at com.jarlen.picturetest.ImageFilterActivity.<init>(ImageFilterActivity.java:40)
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at java.lang.Class.newInstance(Class.java:1572)
            at android.app.Instrumentation.newActivity(Instrumentation.java:1065)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2204)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2363)
            at android.app.ActivityThread.access$800(ActivityThread.java:147)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5235)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:906)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:701)

**Comment by jarlen** [comment]
将library作为库供外面引用，然后clean  rebuld一下，切记不要修改native类的包名。
红米note2 android5.02 OK

**Comment by newtonker** [comment]
@jarlen ，这个工程在Eclipse上，按照你说的library方法是可以正常使用的。在Android Studio中直接跑是有问题的，需要对Photo_Demo和Photo_Library中的build.gradle做修改才行。
相关的问题可以参考：
http://stackoverflow.com/questions/16952388/how-to-change-libs-directory-in-gradle/16993006#16993006
具体的修改方法是：
在上述两个文件夹中的build.gradle里的android->sourceSets->main下增加main.jniLibs.srcDirs=['libs']

**Comment by jarlen** [comment]
I know ,针对这个demo只能在eclipse上跑，没做studio兼容，sorry
但做起来很简单。
