### ISSUE TITLE
调用涂鸦功能会有几率崩溃

### ISSUE THREAD

**Issue by LcTerry** [jarlen/PhotoEditDemo#10]
`java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference
	at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1269)
	at android.graphics.Canvas.drawBitmap(Canvas.java:1325)
	at com.js.photosdk.scrawl.DrawingBoardView.onDraw(DrawingBoardView.java:59)
	at android.view.View.draw(View.java:16435)
	at android.view.View.updateDisplayListIfDirty(View.java:15388)
	at android.view.View.draw(View.java:16189)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15380)
	at android.view.View.draw(View.java:16189)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15380)
	at android.view.View.draw(View.java:16189)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15380)
	at android.view.View.draw(View.java:16189)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15380)
	at android.view.View.draw(View.java:16189)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15380)
	at android.view.View.draw(View.java:16189)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at android.view.View.updateDisplayListIfDirty(View.java:15380)
	at android.view.View.draw(View.java:16189)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3735)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
	at com.android.internal.policy.PhoneWindow$DecorView.dispatchDraw(PhoneWindow.java:2768)
	at android.view.View.draw(View.java:16447)
	at com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2754)
	at android.view.View.updateDisplayListIfDirty(View.java:15388)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:286)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:292)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:327)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:3025)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2829)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2441)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1323)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6713)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
	at android.view.Choreographer.doCallbacks(Choreographer.java:696)
	at android.view.Choreographer.doFrame(Choreographer.java:631)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5728)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)`

**Comment by jarlen** [comment]
@LcTerry 你好，这个好久没有维护了，不是产品级别的demo，请自行修复，不好意思
